apiVersion: v1
kind: Secret
metadata:
  name: ocir-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ1cy1jaGljYWdvLTEub2Npci5pbyI6eyJ1c2VybmFtZSI6InJhZmFzYW4vYXh5ZTZtZWwxbDBuIiwicGFzc3dvcmQiOiI2T1kudVk3O0hNOztlQnlhZDlhSCIsImVtYWlsIjoiemxvdnRuaWtAb3V0bG9vay5jb20iLCJhdXRoIjoiY21GbVlYTmhiaTloZUhsbE5tMWxiREZzTUc0Nk5rOVpMblZaTnp0SVRUczdaVUo1WVdRNVlVZz0ifX19
